// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9HFum6vn6kXLfIRcIpCptcJnBOwGOURs',
    appId: '1:134421739723:web:2a0bd28ccc90a3a036034e',
    messagingSenderId: '134421739723',
    projectId: 'fluuter1-78c68',
    authDomain: 'fluuter1-78c68.firebaseapp.com',
    storageBucket: 'fluuter1-78c68.firebasestorage.app',
    measurementId: 'G-T6ZWMBFYXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBQA5xcspu-T99NWXT8tNCY0_u3cHk99w',
    appId: '1:134421739723:android:bcb3fa7b93212ccd36034e',
    messagingSenderId: '134421739723',
    projectId: 'fluuter1-78c68',
    storageBucket: 'fluuter1-78c68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC_mWx7w6kquQNIFcfd59iDpEnuov1E9A',
    appId: '1:134421739723:ios:39d76471fc0f091b36034e',
    messagingSenderId: '134421739723',
    projectId: 'fluuter1-78c68',
    storageBucket: 'fluuter1-78c68.firebasestorage.app',
    iosBundleId: 'com.example.quick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC_mWx7w6kquQNIFcfd59iDpEnuov1E9A',
    appId: '1:134421739723:ios:39d76471fc0f091b36034e',
    messagingSenderId: '134421739723',
    projectId: 'fluuter1-78c68',
    storageBucket: 'fluuter1-78c68.firebasestorage.app',
    iosBundleId: 'com.example.quick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9HFum6vn6kXLfIRcIpCptcJnBOwGOURs',
    appId: '1:134421739723:web:9f5d503ad5aa71c136034e',
    messagingSenderId: '134421739723',
    projectId: 'fluuter1-78c68',
    authDomain: 'fluuter1-78c68.firebaseapp.com',
    storageBucket: 'fluuter1-78c68.firebasestorage.app',
    measurementId: 'G-BRJRDM49P4',
  );
}
